
if(CMAKE_COMPILER_IS_GNUCC)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall")
    if(WIN32)
        set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -mconsole -static-libgcc")
    endif()
elseif(MSVC)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /MT")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /MANIFEST:NO /SUBSYSTEM:CONSOLE")
    add_definitions(/D_CRT_SECURE_NO_WARNINGS)
endif()


link_libraries(ex_test)

add_executable(test-buffer acutest.h test-buffer.c)
add_executable(test-cmdline acutest.h test-cmdline.c)
add_executable(test-crc32 acutest.h test-crc32.c)
add_executable(test-defs acutest.h test-defs.c)
add_executable(test-fnv acutest.h test-fnv.c)
add_executable(test-goodalloc acutest.h test-goodalloc.c)
add_executable(test-list acutest.h test-list.c)
add_executable(test-malloca acutest.h test-malloca.c)
add_executable(test-memchunk acutest.h test-memchunk.c)
if(WIN32)
add_executable(test-memstream acutest.h test-memstream.c)
endif()
add_executable(test-murmur acutest.h test-murmur.c)
add_executable(test-rbtree acutest.h test-rbtree.c)
